services:
  backend:
    container_name: dashboard-backend
    image: ghcr.io/iseu-desarrollo-maro/dashboard-backend:latest
    # En Azure no exponemos el puerto del backend al público
    expose:
      - "7001"
    environment:
      - FRONTEND_URL=https://mi-proyecto-rust-flask-frontend.azurewebsites.net
      - GITHUB_ORG=iseu-desarrollo-maro
      - PORT=7001
    restart: unless-stopped

  frontend:
    container_name: dashboard-frontend
    image: ghcr.io/iseu-desarrollo-maro/dashboard-frontend:latest
    ports:
      - "5001:5001"
    environment:
      - API_URL=https://mi-proyecto-rust-flask.azurewebsites.net
      - GITHUB_ORG=iseu-desarrollo-maro
    depends_on:
      - backend
