name: CI/CD Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          # Backend
          docker build -t ghcr.io/${{ github.repository_owner }}/dashboard-backend:latest \
                       -t ghcr.io/${{ github.repository_owner }}/dashboard-backend:${{ github.ref_name }} ./app
          docker push ghcr.io/${{ github.repository_owner }}/dashboard-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/dashboard-backend:${{ github.ref_name }}

          # Frontend
          docker build -t ghcr.io/${{ github.repository_owner }}/dashboard-frontend:latest \
                       -t ghcr.io/${{ github.repository_owner }}/dashboard-frontend:${{ github.ref_name }} .
          docker push ghcr.io/${{ github.repository_owner }}/dashboard-frontend:latest
          docker push ghcr.io/${{ github.repository_owner }}/dashboard-frontend:${{ github.ref_name }}

  deploy-to-azure:
    name: Deploy to Azure App Service
    needs: build-and-push-images # Depende del job que construye y sube las imágenes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Usamos el Service Principal

      - name: Deploy Backend (Rust)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "mi-proyecto-rust-flask"
          # Ya no necesitamos publish-profile, Azure Login se encarga
          images: ghcr.io/${{ github.repository_owner }}/dashboard-backend:${{ github.ref_name }}

      - name: Deploy Frontend (Python)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "mi-proyecto-rust-flask-frontend"
          # Ya no necesitamos publish-profile, Azure Login se encarga
          images: ghcr.io/${{ github.repository_owner }}/dashboard-frontend:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
